### PR TITLE
Add quit buttons

### LINKED ISSUE #432: Fix Webinterface - Quit buttons
Playtesting showed that we need a way to quit the game. Without this feature, mobile phones that connected before will reconnect and fill a spot in the max player count, making the setup before a game finicky. This task is to address that problem.

This is a subtask of #429 - Fix Webinterface

### PR DESCRIPTION
**Pull request by Geweldig**
Adds quit buttons to the necessary views.
Also disabled the "No Team" button once you join a team.

Closes #432

### CODE REVIEW

**Comment by ChielBruin** [comment]
Looks good! can be merged

**Comment by Diocruel** [comment]
Testing it out on iOS

**Comment by Diocruel** [comment]
It seems that the pause screen and quit button work fin in the menu level, win and lose level.
In the tutorial level the button shows up, but when pressing quit the screen exits to the cave of caerbannog start screen (when you first log in to the web page) and still has the disable full screen and quit button on top of the instructions button.

**Comment by Geweldig** [comment]
That is a bug I knew about but had completely forgotten about, thanks for reminding me!

**Comment by Diocruel** [comment]
I forgot to add that in the main maze level pausing the game does nothing on the web interface on iOS and of course there is no quit button.

**Comment by Diocruel** [comment]
Can be merged now.

**Pull request merged**
