### PR TITLE
Added Sprint 7 backlog

### PR DESCRIPTION
**Pull request by Taeir**
The backlog of sprint 7.

### CODE REVIEW

**Comment by ChielBruin** [comment]
Looks good can be merged!

**Comment by BCrlrd** [comment]
Looks good, can be merged.

**Comment by Geweldig** [comment]
Once a table containing the total hours for everyone person has been added this can be merged in my opinion.

**Comment by Geweldig** [comment]
Can and should be merged once travis is done.

**Comment by ChielBruin** [comment]
@BCrlrd i totaly missed that!

**Pull request merged**
