### PR TITLE
Added the updated EAD

### PR DESCRIPTION
**Pull request by ChielBruin**
Added the ead and a bigger image of the UML

### CODE REVIEW

**Comment by Diocruel** [comment]
Nice inclusion of the bigger image of the uml!

**Comment by Diocruel** [comment]
Perhaps link the UML in the document?

**Comment by Diocruel** [comment]
For the rest it looks fine.

**Comment by Taeir** [comment]
Apart from one small typo, this looks good and can be merged.

EDIT: Typo has been fixed now, can be merged.

**Comment by ChielBruin** [comment]
@Diocruel I mentioned that the image is also in the documentation folder

**Pull request merged**
