### PR TITLE
Done and done (Sprint 5 retrospective + Sprint 6 backlog).

### PR DESCRIPTION
**Pull request by Taeir**
- Changed version to 0.5.0.
- Added Sprint 5 retrospect
- Added Sprint 6 backlog

### CODE REVIEW

**Comment by ChielBruin** [comment]
My tasks are missing in the backlog

**Comment by Taeir** [comment]
I have noticed some things that are wrong, and I am fixing them.

**Comment by Geweldig** [comment]
Can be merged after those fixes have been applied!

**Comment by ChielBruin** [comment]
Looks good now

**Comment by Geweldig** [comment]
Will merge once travis is done.

**Comment by Diocruel** [comment]
Looks good! :)

**Pull request merged**
