### PR TITLE
Add new EAD

### PR DESCRIPTION
**Pull request by Geweldig**
Adds an updated EAD.
NOTE: As a lot will be changed in the current sprint the EAD is slightly
lacking.

### CODE REVIEW

**Comment by Diocruel** [comment]
2.2.1 communication 3 a: what is phase 1 here? phase 1 does not exist, and it makes no sense to do step 1 here.

**Comment by Diocruel** [comment]
Map should be it's own chapter with the remark that it is not updated yet because the maze generation update branch will not be included on master this sprint.

**Comment by Diocruel** [comment]
Rooms are not stored in XML json files, they are stored in .crf files, carbaernog room files, and maps are stored as a map/shallow tree structure with an a .cmf file, caerbannog  map files.

**Comment by Diocruel** [comment]
WE do not yet store settings in any files except the classes

**Comment by Diocruel** [comment]
the map part should be move to maze generation

**Comment by Diocruel** [comment]
Good job on the rest. I think the suggested fixes should be implemented before fixing.

**Comment by ChielBruin** [comment]
Apart from the suggestionsm made by robin, it looks good

**Comment by Diocruel** [comment]
Can be merged now.

**Comment by ChielBruin** [comment]
I agree

**Pull request merged**
