### PR TITLE
Feature more rooms

### PR DESCRIPTION
**Pull request by WytzeElhorst**
Adds 20 rooms to the game

### CODE REVIEW

**Comment by Diocruel** [comment]
Two things:
1. please add a newline to all newly added room files,
2. why is the height of the torch different?

**Comment by Geweldig** [comment]
Newline in room files are not needed. That being said, this can be merged.

**Comment by WytzeElhorst** [comment]
the torchheight is different because the lamp was hovering a bit under the ceiling and now it's properly attached

**Comment by Taeir** [comment]
I think lights should be attached to the ceiling, so I think the new height is good.

**Comment by Diocruel** [comment]
Okay, per majority vote I agree. Merging.

**Pull request merged**
