### PR TITLE
Refactor framework

### LINKED ISSUE #90: Refactor framework

### LINKED ISSUE #96: Add Game State and Object
Expand the framework to support Game states.
Refactor the code to have a proper Game class. 
subtask of: #95, #90

### LINKED ISSUE #97: Improve Package Structure
Divide the code into packages.
Subtask of: #90

### PR DESCRIPTION
**Pull request by ChielBruin**
- Refactored the framework to use controllers. [e54df22]
- Organized the packages. [834c047]
- Created a proper Game class. [6824f43]

Additional features:
- Introduced TickListeners that receive update-calls. [583a53c]
- Introduced gamestate to indicate the state of the game. [d175ebe]
- Added the option to pause the game (using 'P'). [253c6d2]
- Added option to show the statView (now hidden by default). [20a3a95]
- Includes more advanced maze generation. [124672e]

NOTE: This pull request is merging in dev-sprint3 and not in master. Tests are not included as they will have their own pr in the future. Collision support will also be added shortly.
This pull request closes #90, closes #96 and closes #97.

### CODE REVIEW

**Comment by Geweldig** [comment]
As this is not getting merged into master i'm fine with adding this to the dev branch for further expansion. I have no complaints about any of the code.

**Comment by ChielBruin** [comment]
I made a quick fix for a bug i've found.

**Comment by Geweldig** [comment]
I didn't notice that whille looking through the code. This just saved us a lot of time, as we would probably get extremely confused when this happened in the future. Nice!

**Comment by Taeir** [comment]
Looks good Chiel, the framework was in dire need of an update.
Just don't forget to remove that fully commented out file when we conclude that we no longer need it.

**Comment by Geweldig** [comment]
I was the one that completely commented that out. The reason it's still there is because some of the tests and basic functionality can probably still be used in what I'm working on, so it's easier to store it like this than keeping it on a different branch.

**Pull request merged**
