### PR TITLE
Added the new backlog

### PR DESCRIPTION
**Pull request by ChielBruin**
Added the backlog for sprint 4

### CODE REVIEW

**Comment by Diocruel** [comment]
There are some errors in the look of the pdf, but the tekst is correct. See:
https://github.com/Taeir/ContextProject-MIGI2/blob/19de0fed8fadcc457fce68c41059e046e6e203e9/documentation/sprint%204/Sprint%204%20Backlog.pdf

**Comment by Diocruel** [comment]
I think we should merge it though because of deadlines, and it is only a slight grey mismatch.

**Comment by Taeir** [comment]
I am quite responsible it seems :P

The user stories and issue descriptions look very good and are very extensive, well done! I think this can be merged.

**Comment by Diocruel** [comment]
Lead programmer is pretty important when everybody has to program...

**Comment by Taeir** [comment]
@diocruel yeah, it's a minor graphical error, I don't think it needs to be changed.

**Pull request merged**
