### PR TITLE
Fix balance

### LINKED ISSUE #391: Balancing - Adjust constants/settings based on player feedback.
Adjust settings and numbers based on feedback

This is a subtask of #390 - Balancing

### PR DESCRIPTION
**Pull request by WytzeElhorst**
playerspeed and jump down, explorationradius up, bunnies stronger and roof looks like walls.

This closes #391.

### CODE REVIEW

**Comment by ChielBruin** [comment]
Looks good! can be merged

**Comment by Diocruel** [comment]
Seems Like some test are failing tough, so please fix them. :)

**Comment by Geweldig** [comment]
should be merged

**Comment by Diocruel** [comment]
Can be merged now

**Pull request merged**
