### PR TITLE
Add overview

### LINKED ISSUE #431: Fix Webinterface - Overview Map
Playtesting showed that a mobile screen is quite small and that it is easy to lose the player on the screen. Therefore, this task is the addition of an overview map. Players will be able to toggle to the overview and back.

This is a subtask of #429 - Fix Webinterface

### PR DESCRIPTION
**Pull request by Geweldig**
You can now switch to an overview by pinching out.

Closes #431

### CODE REVIEW

**Comment by Diocruel** [comment]
This does not seem to work on iOS devices, so I'm afraid I can't comment on this PR

**Comment by Taeir** [comment]
@Diocruel I can confirm that it works on my ipad 1 with iOS 5.0 after the fix (the game doesn't, but the zooming does), so it's most likely that it work for you as well now.

**Comment by Diocruel** [comment]
Pitching now works on iOS, with chrome and safari! :dancer: 
Perhaps add a empty line at the end of index.html to prevent merge conflicts in the further, but for the rest it looks good to merge.

**Comment by Geweldig** [comment]
I agree with @Taeir's changes to this branch. If he also agrees with my additions this can be merged.

**Comment by Taeir** [comment]
I agree, can be merged.

**Pull request merged**
