### PR TITLE
Refactor cleanup

### PR DESCRIPTION
**Pull request by Taeir**
Removed DrawableFilter and RandomLevelFactory, as they are no longer used.

### CODE REVIEW

**Comment by Geweldig** [comment]
GeneratorRoom should also be removed, as this is only used by this version of the RandomLevelFactory

**Comment by ChielBruin** [comment]
The folder 'rooms' in resources should also be removed, as this is only used by the old maze generation that you removed in this pr. The rest looks good

**Comment by Geweldig** [comment]
Can and should be merged now.

**Comment by Diocruel** [comment]
Merging now. Code is no longer used.

**Pull request merged**
