### PR TITLE
Assets art

### LINKED ISSUE #451: Artwork - Wallframes
Create better artwork that is displayed in the different wallframes in the game.

This is a subtask of #448 - Artwork

### LINKED ISSUE #452: Artwork - Tutorial
Create missing images for the tutorial, and improve some of the existing tutorial images.

This is a subtask of #448 - Artwork

### PR DESCRIPTION
**Pull request by WytzeElhorst**
Replaces all placeholder art with new pictures and also fixes the backward wallframe in the tutorial level.

This closes #451, closes #452.

### CODE REVIEW

**Comment by Diocruel** [comment]
The restart art asset contains an error. There is a blue part in an e.

This is both in the restart of the Win level and the Lose level

**Comment by Diocruel** [comment]
The ? should be explained somehow, though I'm not sure what was meant in most images. The pitfall image also contains a ?, but you could have some cartoony pitfall here.

**Comment by Diocruel** [comment]
I'll review this PR with the Oculus, until that I cannot be sure if this can be merged. However, the art looks really good! I like the font of the letters used, the background and the new shiny Knight of Camelot!

**Comment by WytzeElhorst** [comment]
I kept the pitfall explanation kind of vague on purpose to go along with the fact that they're invisible to keep them a bit mysterious and as soon as a player will fall into one they will figure out what happened quickly

**Comment by Diocruel** [comment]
Okay, it looks amazing in VR, can be merged now imo.

**Comment by ChielBruin** [comment]
Looks great! I will merge it

**Pull request merged**
