### PR TITLE
The end is nigh. (Move changes from dev-sprint5 to master)

### PR DESCRIPTION
**Pull request by Taeir**
All these changes have already been reviewed on the development branch.

Cobertura reports 84% line coverage.

**Note that the NoVRMouseManager is for development only (adds mouse controls when no VR is attached), and will not be in the final product. As such, it is untested, which is one of the reasons our coverage is lower.**

### CODE REVIEW

**Comment by Taeir** [comment]
Please wait until #319 has been merged.

**Comment by ChielBruin** [comment]
Looks good. Now we wait...

**Comment by Geweldig** [comment]
Can be merged now.

**Comment by Diocruel** [comment]
I'll shall also give my approval for this merge _raises magic wand and touches pull request_

**Pull request merged**
