### PR TITLE
Add Codecov to repository and travis

### PR DESCRIPTION
**Pull request by Taeir**
Codecov is a tool that gives static analysis reports on pull requests and more fancy stuff. This adds the codecov functionality to our repository.

### CODE REVIEW

**Comment by Geweldig** [comment]
Am I correct in believing this doesn't add the codecov badge to our readme? If that's the case I don't really see the point in adding this to our repository.

**Comment by Taeir** [comment]
@BCrlrd You are right, I addressed that issue with the commit above.

**Comment by Geweldig** [comment]
@Taeir Ah great. In that case I'm fine with merging this, should make for a nicer overview of our project.

**Comment by ChielBruin** [comment]
Nice addition! I will merge it.

**Pull request merged**
